FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

ARG NODE_ENV=production
RUN if [ "$NODE_ENV" = "production" ]; then npm install --only=production; else npm install; fi

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
