FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY package*.json ./
COPY tsconfig.json ./
COPY .env ./

RUN npm install

COPY ./scripts/start-with-prisma.sh ./scripts/ 
RUN chmod +x ./scripts/start-with-prisma.sh

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "./scripts/start-with-prisma.sh"]
