FROM dpage/pgadmin4:latest

# Copy the pgAdmin setup script or configuration files
COPY pgadmin_setup.sh /docker-entrypoint-initdb.d/pgadmin_setup.sh

# Optionally set any other environment variables
ENV PGADMIN_DEFAULT_EMAIL=fulano@gmail.com
ENV PGADMIN_DEFAULT_PASSWORD=abc123